server:
  port: 9099
  

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Post
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: LIKECOMMENT-SERVICE

  properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  
app:
 config : PostService/postservice/config/configuration

logging:
  config: PostService/postservice/config/applicationallLogs.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  # instance:
  #   hostname: localhost
  #   prefer-ip-address: true
  #   lease-renewal-interval-in-seconds: 10
  #   lease-expiration-duration-in-seconds: 15
  #   instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


#  resiliance4 j

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
      enabled: true
  
#  circuitbreaker:

resilience4j:
  circuitbreaker:
    instances:
      likeCommentServiceCircuitBreaker:
        registerHealthIndicator: true
        sliding-window-type: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true


#  Resiliance4j Time out 

  timelimiter:
    instances:
      likeCommentServiceTimeLimiter:
        timeoutDuration: 10s


# Retry
  retry.instances:
    likeCommentServiceRetry:
      maxAttempts: 5
      waitDuration: 3s
      